Repository AlesInfiny/maris, pull requests merged in 2024-12, with the labels that each got.

#2187 Dresscaのコメント誤りを訂正
  samples/Dressca/dressca-backend/src/Dressca.ApplicationCore/ApplicationService/CatalogApplicationService.cs
  samples/Dressca/dressca-frontend/admin/src/services/catalog/catalog-service.ts
Labels: target: Dressca, 内部の改善

#2191 build-documents-ci.yml にpermissionを明示的に設定する
  .github/workflows/build-documents-ci.yml
Labels: CI/CD, 内部の改善

#2196 ObjectExtentionsの名前空間をSystemに変更
  samples/Dressca/dressca-backend/src/Dressca.ApplicationCore/Ordering/OrderFactory.cs
  samples/Dressca/dressca-backend/src/Dressca.SystemCommon/ObjectExtensions.cs
  samples/Dressca/dressca-backend/src/Dressca.Web.Consumer/Controllers/BasketItemsController.cs
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.SystemCommon/ObjectExtensionsTest.cs
Labels: target: Dressca, 内部の改善

#2194 remove-old-artifacts.yml にpermissionを明示的に設定する
  .github/workflows/remove-old-artifacts.yml
Labels: CI/CD, 内部の改善

#2192 アセットコードから改行文字を取り除いてからログ出力する
  samples/Dressca/dressca-backend/src/Dressca.ApplicationCore/ApplicationService/AssetApplicationService.cs
  samples/Dressca/dressca-backend/src/Dressca.EfInfrastructure/Migrations/20241211091203_InitialCreate.cs
  samples/Dressca/dressca-backend/src/Dressca.SystemCommon/StringExtentions.cs
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.SystemCommon/StringExtentionsTest.cs
Labels: 不具合, target: Dressca

#2199 samples-dressca-admin-frontend.ci.yml にpermissionを明示的に設定する
  .github/workflows/samples-dressca-admin-frontend.ci.yml
Labels: CI/CD, 内部の改善

#2201 samples-azure-ad-b2c-auth-ci.ymlにpermissionを明示的に設定する
  .github/workflows/samples-azure-ad-b2c-auth-ci.yml
Labels: CI/CD, 内部の改善

#2203 samples-dressca-consumer-frontend.ci.ymlにpermissionを明示的に設定する
  .github/workflows/samples-dressca-consumer-frontend.ci.yml
Labels: CI/CD, 内部の改善

#2204 remove-old-artifacts.ymlにactionsのpermissionsを追加
  .github/workflows/remove-old-artifacts.yml
Labels: CI/CD, 内部の改善
