Repository AlesInfiny/maris, pull requests merged in 2025-03, with the labels that each got.

#2454 略語の登録手順をREADMEに追記
  documents/README.md
  documents/readme-images/abbreviations-setting-result.png
Labels: 内部の改善

#2492 ドキュメントで「フロントエンド」と「クライアントサイド」、「バックエンド」と「サーバーサイド」を使い分けるように修正
  documents/contents/app-architecture/client-side-rendering/global-function/exception-handling.md
  documents/contents/app-architecture/client-side-rendering/global-function/index.md
  documents/contents/app-architecture/client-side-rendering/global-function/logging-policy.md
  documents/contents/app-architecture/client-side-rendering/global-function/validation-policy.md
  documents/contents/guidebooks/how-to-develop/dotnet/configure-asp-net-core-web-api-project.md
  documents/contents/guidebooks/how-to-develop/dotnet/configure-asp-net-core-with-vite-project.md
  documents/contents/guidebooks/how-to-develop/dotnet/configure-integration-test-project.md
  documents/contents/guidebooks/how-to-develop/dotnet/create-project-structure.md
  documents/contents/guidebooks/how-to-develop/dotnet/create-project.md
  documents/contents/guidebooks/how-to-develop/dotnet/create-solution-structure.md
  documents/contents/guidebooks/how-to-develop/dotnet/health-check-api.md
  documents/contents/guidebooks/how-to-develop/dotnet/index.md
  documents/contents/guidebooks/how-to-develop/dotnet/preparation.md
  documents/contents/guidebooks/how-to-develop/dotnet/project-settings.md
  documents/contents/guidebooks/how-to-develop/publication/index.md
  documents/contents/guidebooks/how-to-develop/vue-js/create-api-client-code.md
  documents/contents/guidebooks/how-to-develop/vue-js/create-vuejs-blank-project.md
  documents/contents/guidebooks/how-to-develop/vue-js/css.md
  documents/contents/guidebooks/how-to-develop/vue-js/folder-structure-of-blank-project.md
  documents/contents/guidebooks/how-to-develop/vue-js/index.md
  documents/contents/guidebooks/how-to-develop/vue-js/input-validation.md
  documents/contents/guidebooks/how-to-develop/vue-js/optional-packages.md
  documents/contents/guidebooks/how-to-develop/vue-js/project-settings.md
  documents/contents/guidebooks/how-to-develop/vue-js/setting-workspaces.md
  documents/contents/guidebooks/how-to-develop/vue-js/static-verification-and-format.md
  documents/contents/index.md
Labels: 不具合

#2515 Dresscaをxunit v3に更新する
  .github/workflows/samples-dressca-admin-backend.ci.yml
  .github/workflows/samples-dressca-consumer-backend.ci.yml
  samples/Dressca/dressca-backend/Directory.Packages.props
  samples/Dressca/dressca-backend/Dressca.sln
  samples/Dressca/dressca-backend/src/Maris.Logging.Testing/Maris.Logging.Testing.csproj
  samples/Dressca/dressca-backend/src/Maris.Logging.Testing/Xunit/TestLoggerManager.cs
  samples/Dressca/dressca-backend/src/Maris.Logging.Testing/Xunit/XunitLogger.cs
  samples/Dressca/dressca-backend/src/Maris.Logging.Testing/Xunit/XunitLoggerProvider.cs
  samples/Dressca/dressca-backend/tests/Directory.Build.props
  samples/Dressca/dressca-backend/tests/Dressca.IntegrationTest/DatabaseHealthCheckTest.cs
  samples/Dressca/dressca-backend/tests/Dressca.IntegrationTest/Dressca.IntegrationTest.csproj
  samples/Dressca/dressca-backend/tests/Dressca.IntegrationTest/ShoppingTest.cs
  samples/Dressca/dressca-backend/tests/Dressca.IntegrationTest/xunit.runner.json
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.ApplicationCore/ApplicationService/AssetApplicationServiceTest.cs
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.ApplicationCore/ApplicationService/CatalogApplicationServiceTest.cs
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.ApplicationCore/ApplicationService/OrderApplicationServiceTest.cs
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.ApplicationCore/ApplicationService/ShoppingApplicationServiceTest.cs
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.ApplicationCore/Catalog/CatalogDomainServiceTest.cs
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.ApplicationCore/Dressca.UnitTests.ApplicationCore.csproj
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.ApplicationCore/Ordering/OrderTest.cs
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.ApplicationCore/TestBase.cs
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.ApplicationCore/xunit.runner.json
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.SystemCommon/Dressca.UnitTests.SystemCommon.csproj
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.SystemCommon/xunit.runner.json
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.Web.Admin/Dressca.UnitTests.Web.Admin.csproj
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.Web.Admin/DummyTest.cs
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.Web.Admin/TestBase.cs
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.Web.Admin/xunit.runner.json
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.Web.Consumer/Dressca.UnitTests.Web.Consumer.csproj
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.Web.Consumer/TestBase.cs
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.Web.Consumer/xunit.runner.json
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.Web/Dressca.UnitTests.Web.csproj
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.Web/Runtime/BusinessExceptionDevelopmentFilterTest.cs
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.Web/Runtime/BusinessExceptionFilterTest.cs
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.Web/Runtime/DbUpdateConcurrencyExceptionDevelopmentFilterTest.cs
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.Web/Runtime/DbUpdateConcurrencyExceptionFilterTest.cs
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.Web/TestBase.cs
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.Web/xunit.runner.json
  samples/Dressca/dressca-backend/tests/Dressca.Web.Admin.IntegrationTest/DatabaseHealthCheckTest.cs
  samples/Dressca/dressca-backend/tests/Dressca.Web.Admin.IntegrationTest/Dressca.Web.Admin.IntegrationTest.csproj
  samples/Dressca/dressca-backend/tests/Dressca.Web.Admin.IntegrationTest/xunit.runner.json
  samples/Dressca/dressca-backend/tests/Maris.Logging.Testing.Tests/Maris.Logging.Testing.Tests.csproj
  samples/Dressca/dressca-backend/tests/Maris.Logging.Testing.Tests/Xunit/FakeLoggingBuilderExtensionsTest.cs
  samples/Dressca/dressca-backend/tests/Maris.Logging.Testing.Tests/Xunit/TestLoggerManagerTest.cs
  samples/Dressca/dressca-backend/tests/Maris.Logging.Testing.Tests/Xunit/TestLoggerServiceCollectionExtensionsTest.cs
  samples/Dressca/dressca-backend/tests/Maris.Logging.Testing.Tests/Xunit/XunitLoggerProviderTest.cs
  samples/Dressca/dressca-backend/tests/Maris.Logging.Testing.Tests/Xunit/XunitLoggerTest.cs
  samples/Dressca/dressca-backend/tests/Maris.Logging.Testing.Tests/Xunit/XunitLoggingBuilderExtensionsTest.cs
  samples/Dressca/dressca-backend/tests/Maris.Logging.Testing.Tests/xunit.runner.json
Labels: target: Dressca

#2510 Snippetsを追加
  documents/.gitignore
  documents/README.md
  documents/contents/samples/console-app-with-di/index.md
  documents/hooks/github_markdown_fetcher.py
  documents/mkdocs.yml
Labels: 内部の改善, target: 管理系ドキュメント, target: サンプル解説

#2541 ConsoleAppWithDIをxunit-v3へ更新する
  .github/workflows/samples-console-app-with-di.ci.yml
  samples/ConsoleAppWithDI/solution/Directory.Packages.props
  samples/ConsoleAppWithDI/solution/src/Maris.ConsoleApp.Hosting/ConsoleAppHostedService.cs
  samples/ConsoleAppWithDI/solution/src/Maris.Logging.Testing/Maris.Logging.Testing.csproj
  samples/ConsoleAppWithDI/solution/src/Maris.Logging.Testing/Xunit/TestLoggerManager.cs
  samples/ConsoleAppWithDI/solution/src/Maris.Logging.Testing/Xunit/XunitLogger.cs
  samples/ConsoleAppWithDI/solution/src/Maris.Logging.Testing/Xunit/XunitLoggerProvider.cs
  samples/ConsoleAppWithDI/solution/tests/Directory.Build.props
  samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.IntegrationTests/Maris.ConsoleApp.IntegrationTests.csproj
  samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.IntegrationTests/ScopeTests/ObjectState.cs
  samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.IntegrationTests/ScopeTests/ScopedTest.cs
  samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.IntegrationTests/ScopeTests/SingletonTest.cs
  samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.IntegrationTests/ScopeTests/TransientTest.cs
  samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.IntegrationTests/TestBase.cs
  samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.UnitTests/Hosting/ConsoleAppContextFactoryTest.cs
  samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.UnitTests/Hosting/ConsoleAppHostedServiceTest.cs
  samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.UnitTests/Hosting/ServiceCollectionExtensionsTest.cs
  samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.UnitTests/Maris.ConsoleApp.UnitTests.csproj
  samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.UnitTests/TestBase.cs
  samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.UnitTests/XunitSerializer/CommandBaseXunitSerializer.cs
  samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.UnitTests/XunitSerializer/ConsoleAppContextXunitSerializer.cs
  samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.UnitTests/XunitSerializer/JsonXunitSerializer.cs
Labels: dependencies, nuget

#2547 Azure AD B2Cサンプルをxunit v3に移行する
  .github/workflows/samples-azure-ad-b2c-auth-ci.yml
  samples/AzureADB2CAuth/auth-backend/Directory.Packages.props
  samples/AzureADB2CAuth/auth-backend/Dressca.sln
  samples/AzureADB2CAuth/auth-backend/tests/Directory.Build.props
  samples/AzureADB2CAuth/auth-backend/tests/Dressca.IntegrationTest/ApiTest.cs
  samples/AzureADB2CAuth/auth-backend/tests/Dressca.IntegrationTest/ApiTestWebApplicationFactory.cs
  samples/AzureADB2CAuth/auth-backend/tests/Dressca.IntegrationTest/Dressca.IntegrationTest.csproj
Labels: CI/CD, target: Azure AD B2C Auth

#2556 DresscaからMaris.Logging.Testingを削除する
  samples/Dressca/dressca-backend/Directory.Packages.props
  samples/Dressca/dressca-backend/Dressca.Web.Admin.slnf
  samples/Dressca/dressca-backend/Dressca.Web.Consumer.slnf
  samples/Dressca/dressca-backend/Dressca.sln
  samples/Dressca/dressca-backend/src/Maris.Logging.Testing/Maris.Logging.Testing.csproj
  samples/Dressca/dressca-backend/src/Maris.Logging.Testing/Xunit/FakeLoggingBuilderExtensions.cs
  samples/Dressca/dressca-backend/src/Maris.Logging.Testing/Xunit/TestLoggerManager.cs
  samples/Dressca/dressca-backend/src/Maris.Logging.Testing/Xunit/TestLoggerServiceCollectionExtensions.cs
  samples/Dressca/dressca-backend/src/Maris.Logging.Testing/Xunit/XunitLogger.cs
  samples/Dressca/dressca-backend/src/Maris.Logging.Testing/Xunit/XunitLoggerProvider.cs
  samples/Dressca/dressca-backend/src/Maris.Logging.Testing/Xunit/XunitLoggingBuilderExtensions.cs
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.ApplicationCore/Dressca.UnitTests.ApplicationCore.csproj
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.Web.Admin/Dressca.UnitTests.Web.Admin.csproj
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.Web.Consumer/Dressca.UnitTests.Web.Consumer.csproj
  samples/Dressca/dressca-backend/tests/Dressca.UnitTests.Web/Dressca.UnitTests.Web.csproj
  samples/Dressca/dressca-backend/tests/Maris.Logging.Testing.Tests/Maris.Logging.Testing.Tests.csproj
  samples/Dressca/dressca-backend/tests/Maris.Logging.Testing.Tests/Xunit/FakeLoggingBuilderExtensionsTest.cs
  samples/Dressca/dressca-backend/tests/Maris.Logging.Testing.Tests/Xunit/TestLoggerManagerTest.cs
  samples/Dressca/dressca-backend/tests/Maris.Logging.Testing.Tests/Xunit/TestLoggerServiceCollectionExtensionsTest.cs
  samples/Dressca/dressca-backend/tests/Maris.Logging.Testing.Tests/Xunit/XunitLoggerProviderTest.cs
  samples/Dressca/dressca-backend/tests/Maris.Logging.Testing.Tests/Xunit/XunitLoggerTest.cs
  samples/Dressca/dressca-backend/tests/Maris.Logging.Testing.Tests/Xunit/XunitLoggingBuilderExtensionsTest.cs
  samples/Dressca/dressca-backend/tests/Maris.Logging.Testing.Tests/xunit.runner.json
Labels: target: Dressca
