Repository AlesInfiny/maris, pull requests merged in 2025-07, with the labels that each got.

#2904 [DOC移植]typescript@5.8.3 にバージョンアップする
  documents/_materials/images/guidebooks/how-to-develop/vue-js/vue-tsconfig-dark.drawio
  documents/_materials/images/guidebooks/how-to-develop/vue-js/vue-tsconfig-light.drawio
  documents/contents/guidebooks/how-to-develop/vue-js/project-settings.md
  documents/contents/images/guidebooks/how-to-develop/vue-js/vue-tsconfig-dark.png
  documents/contents/images/guidebooks/how-to-develop/vue-js/vue-tsconfig-light.png
Labels: target: ガイド/AP開発手順

#2912 [DOC]ブランクプロジェクトのフォルダー構造を最新化
  documents/contents/guidebooks/how-to-develop/vue-js/folder-structure-of-blank-project.md
Labels: target: ガイド/AP開発手順

#2924 [DOC]フロントエンドアプリケーションの実行手順を最新化する
  documents/contents/images/trust-folder.png
  documents/contents/index.md
Labels: target: トップページ/テンプレート

#2950 コードスニペットで拡張子にハイフンを含むファイルを表示できない不具合を修正
  documents/hooks/github_markdown_fetcher.py
Labels: 不具合, 内部の改善

#3003 Azure AD B2Cサンプルのnugetパッケージ更新
  samples/AzureADB2CAuth/auth-backend/Directory.Packages.props
Labels: dependencies, npm, target: Azure AD B2C Auth
